// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface BatchArrivalBillAutoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.BatchArrivalBillAutoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operateType = 1;</code>
   */
  java.lang.String getOperateType();
  /**
   * <code>string operateType = 1;</code>
   */
  com.google.protobuf.ByteString
      getOperateTypeBytes();

  /**
   * <code>string billTypeId = 2;</code>
   */
  java.lang.String getBillTypeId();
  /**
   * <code>string billTypeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getBillTypeIdBytes();

  /**
   * <code>string currBillIdsStr = 3;</code>
   */
  java.lang.String getCurrBillIdsStr();
  /**
   * <code>string currBillIdsStr = 3;</code>
   */
  com.google.protobuf.ByteString
      getCurrBillIdsStrBytes();

  /**
   * <code>string userLogin = 4;</code>
   */
  java.lang.String getUserLogin();
  /**
   * <code>string userLogin = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserLoginBytes();
}
