// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface BatchArrivalBillAutoRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.BatchArrivalBillAutoResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string billJson = 1;</code>
   */
  java.lang.String getBillJson();
  /**
   * <code>string billJson = 1;</code>
   */
  com.google.protobuf.ByteString
      getBillJsonBytes();

  /**
   * <code>string billItemJson = 2;</code>
   */
  java.lang.String getBillItemJson();
  /**
   * <code>string billItemJson = 2;</code>
   */
  com.google.protobuf.ByteString
      getBillItemJsonBytes();

  /**
   * <code>string resultBillId = 3;</code>
   */
  java.lang.String getResultBillId();
  /**
   * <code>string resultBillId = 3;</code>
   */
  com.google.protobuf.ByteString
      getResultBillIdBytes();

  /**
   * <code>string responseMessage = 4;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 4;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>string errorMessage = 5;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 5;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>string infoMessage = 6;</code>
   */
  java.lang.String getInfoMessage();
  /**
   * <code>string infoMessage = 6;</code>
   */
  com.google.protobuf.ByteString
      getInfoMessageBytes();
}
