// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

/**
 * Protobuf type {@code bill.service.v1.BatchArrivalBillAutoReq}
 */
public  final class BatchArrivalBillAutoReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bill.service.v1.BatchArrivalBillAutoReq)
    BatchArrivalBillAutoReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchArrivalBillAutoReq.newBuilder() to construct.
  private BatchArrivalBillAutoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchArrivalBillAutoReq() {
    operateType_ = "";
    billTypeId_ = "";
    currBillIdsStr_ = "";
    userLogin_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatchArrivalBillAutoReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            operateType_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            billTypeId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            currBillIdsStr_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userLogin_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bill.service.v1.Bill.internal_static_bill_service_v1_BatchArrivalBillAutoReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bill.service.v1.Bill.internal_static_bill_service_v1_BatchArrivalBillAutoReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bill.service.v1.BatchArrivalBillAutoReq.class, bill.service.v1.BatchArrivalBillAutoReq.Builder.class);
  }

  public static final int OPERATETYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object operateType_;
  /**
   * <code>string operateType = 1;</code>
   */
  public java.lang.String getOperateType() {
    java.lang.Object ref = operateType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operateType_ = s;
      return s;
    }
  }
  /**
   * <code>string operateType = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOperateTypeBytes() {
    java.lang.Object ref = operateType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operateType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BILLTYPEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object billTypeId_;
  /**
   * <code>string billTypeId = 2;</code>
   */
  public java.lang.String getBillTypeId() {
    java.lang.Object ref = billTypeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      billTypeId_ = s;
      return s;
    }
  }
  /**
   * <code>string billTypeId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBillTypeIdBytes() {
    java.lang.Object ref = billTypeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      billTypeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRBILLIDSSTR_FIELD_NUMBER = 3;
  private volatile java.lang.Object currBillIdsStr_;
  /**
   * <code>string currBillIdsStr = 3;</code>
   */
  public java.lang.String getCurrBillIdsStr() {
    java.lang.Object ref = currBillIdsStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currBillIdsStr_ = s;
      return s;
    }
  }
  /**
   * <code>string currBillIdsStr = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCurrBillIdsStrBytes() {
    java.lang.Object ref = currBillIdsStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currBillIdsStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERLOGIN_FIELD_NUMBER = 4;
  private volatile java.lang.Object userLogin_;
  /**
   * <code>string userLogin = 4;</code>
   */
  public java.lang.String getUserLogin() {
    java.lang.Object ref = userLogin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userLogin_ = s;
      return s;
    }
  }
  /**
   * <code>string userLogin = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserLoginBytes() {
    java.lang.Object ref = userLogin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userLogin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOperateTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operateType_);
    }
    if (!getBillTypeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, billTypeId_);
    }
    if (!getCurrBillIdsStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, currBillIdsStr_);
    }
    if (!getUserLoginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userLogin_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOperateTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operateType_);
    }
    if (!getBillTypeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, billTypeId_);
    }
    if (!getCurrBillIdsStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, currBillIdsStr_);
    }
    if (!getUserLoginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userLogin_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bill.service.v1.BatchArrivalBillAutoReq)) {
      return super.equals(obj);
    }
    bill.service.v1.BatchArrivalBillAutoReq other = (bill.service.v1.BatchArrivalBillAutoReq) obj;

    boolean result = true;
    result = result && getOperateType()
        .equals(other.getOperateType());
    result = result && getBillTypeId()
        .equals(other.getBillTypeId());
    result = result && getCurrBillIdsStr()
        .equals(other.getCurrBillIdsStr());
    result = result && getUserLogin()
        .equals(other.getUserLogin());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOperateType().hashCode();
    hash = (37 * hash) + BILLTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + getBillTypeId().hashCode();
    hash = (37 * hash) + CURRBILLIDSSTR_FIELD_NUMBER;
    hash = (53 * hash) + getCurrBillIdsStr().hashCode();
    hash = (37 * hash) + USERLOGIN_FIELD_NUMBER;
    hash = (53 * hash) + getUserLogin().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bill.service.v1.BatchArrivalBillAutoReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bill.service.v1.BatchArrivalBillAutoReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bill.service.v1.BatchArrivalBillAutoReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bill.service.v1.BatchArrivalBillAutoReq)
      bill.service.v1.BatchArrivalBillAutoReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_BatchArrivalBillAutoReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_BatchArrivalBillAutoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bill.service.v1.BatchArrivalBillAutoReq.class, bill.service.v1.BatchArrivalBillAutoReq.Builder.class);
    }

    // Construct using bill.service.v1.BatchArrivalBillAutoReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      operateType_ = "";

      billTypeId_ = "";

      currBillIdsStr_ = "";

      userLogin_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_BatchArrivalBillAutoReq_descriptor;
    }

    public bill.service.v1.BatchArrivalBillAutoReq getDefaultInstanceForType() {
      return bill.service.v1.BatchArrivalBillAutoReq.getDefaultInstance();
    }

    public bill.service.v1.BatchArrivalBillAutoReq build() {
      bill.service.v1.BatchArrivalBillAutoReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bill.service.v1.BatchArrivalBillAutoReq buildPartial() {
      bill.service.v1.BatchArrivalBillAutoReq result = new bill.service.v1.BatchArrivalBillAutoReq(this);
      result.operateType_ = operateType_;
      result.billTypeId_ = billTypeId_;
      result.currBillIdsStr_ = currBillIdsStr_;
      result.userLogin_ = userLogin_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bill.service.v1.BatchArrivalBillAutoReq) {
        return mergeFrom((bill.service.v1.BatchArrivalBillAutoReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bill.service.v1.BatchArrivalBillAutoReq other) {
      if (other == bill.service.v1.BatchArrivalBillAutoReq.getDefaultInstance()) return this;
      if (!other.getOperateType().isEmpty()) {
        operateType_ = other.operateType_;
        onChanged();
      }
      if (!other.getBillTypeId().isEmpty()) {
        billTypeId_ = other.billTypeId_;
        onChanged();
      }
      if (!other.getCurrBillIdsStr().isEmpty()) {
        currBillIdsStr_ = other.currBillIdsStr_;
        onChanged();
      }
      if (!other.getUserLogin().isEmpty()) {
        userLogin_ = other.userLogin_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bill.service.v1.BatchArrivalBillAutoReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bill.service.v1.BatchArrivalBillAutoReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object operateType_ = "";
    /**
     * <code>string operateType = 1;</code>
     */
    public java.lang.String getOperateType() {
      java.lang.Object ref = operateType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operateType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operateType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperateTypeBytes() {
      java.lang.Object ref = operateType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operateType = 1;</code>
     */
    public Builder setOperateType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operateType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string operateType = 1;</code>
     */
    public Builder clearOperateType() {
      
      operateType_ = getDefaultInstance().getOperateType();
      onChanged();
      return this;
    }
    /**
     * <code>string operateType = 1;</code>
     */
    public Builder setOperateTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operateType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object billTypeId_ = "";
    /**
     * <code>string billTypeId = 2;</code>
     */
    public java.lang.String getBillTypeId() {
      java.lang.Object ref = billTypeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billTypeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBillTypeIdBytes() {
      java.lang.Object ref = billTypeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public Builder setBillTypeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      billTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public Builder clearBillTypeId() {
      
      billTypeId_ = getDefaultInstance().getBillTypeId();
      onChanged();
      return this;
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public Builder setBillTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      billTypeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currBillIdsStr_ = "";
    /**
     * <code>string currBillIdsStr = 3;</code>
     */
    public java.lang.String getCurrBillIdsStr() {
      java.lang.Object ref = currBillIdsStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currBillIdsStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currBillIdsStr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCurrBillIdsStrBytes() {
      java.lang.Object ref = currBillIdsStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currBillIdsStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currBillIdsStr = 3;</code>
     */
    public Builder setCurrBillIdsStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currBillIdsStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currBillIdsStr = 3;</code>
     */
    public Builder clearCurrBillIdsStr() {
      
      currBillIdsStr_ = getDefaultInstance().getCurrBillIdsStr();
      onChanged();
      return this;
    }
    /**
     * <code>string currBillIdsStr = 3;</code>
     */
    public Builder setCurrBillIdsStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currBillIdsStr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userLogin_ = "";
    /**
     * <code>string userLogin = 4;</code>
     */
    public java.lang.String getUserLogin() {
      java.lang.Object ref = userLogin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLogin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userLogin = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserLoginBytes() {
      java.lang.Object ref = userLogin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLogin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userLogin = 4;</code>
     */
    public Builder setUserLogin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userLogin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userLogin = 4;</code>
     */
    public Builder clearUserLogin() {
      
      userLogin_ = getDefaultInstance().getUserLogin();
      onChanged();
      return this;
    }
    /**
     * <code>string userLogin = 4;</code>
     */
    public Builder setUserLoginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userLogin_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bill.service.v1.BatchArrivalBillAutoReq)
  }

  // @@protoc_insertion_point(class_scope:bill.service.v1.BatchArrivalBillAutoReq)
  private static final bill.service.v1.BatchArrivalBillAutoReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bill.service.v1.BatchArrivalBillAutoReq();
  }

  public static bill.service.v1.BatchArrivalBillAutoReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchArrivalBillAutoReq>
      PARSER = new com.google.protobuf.AbstractParser<BatchArrivalBillAutoReq>() {
    public BatchArrivalBillAutoReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatchArrivalBillAutoReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatchArrivalBillAutoReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchArrivalBillAutoReq> getParserForType() {
    return PARSER;
  }

  public bill.service.v1.BatchArrivalBillAutoReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

