// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface BillSerialNumberCheckRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.BillSerialNumberCheckResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string returnStr = 1;</code>
   */
  java.lang.String getReturnStr();
  /**
   * <code>string returnStr = 1;</code>
   */
  com.google.protobuf.ByteString
      getReturnStrBytes();
}
