// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface BillQueryUpdateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.BillQueryUpdateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string billTypeId = 1;</code>
   */
  java.lang.String getBillTypeId();
  /**
   * <code>string billTypeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBillTypeIdBytes();

  /**
   * <code>string ddTenantId = 2;</code>
   */
  java.lang.String getDdTenantId();
  /**
   * <code>string ddTenantId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDdTenantIdBytes();

  /**
   * <code>string billJson = 3;</code>
   */
  java.lang.String getBillJson();
  /**
   * <code>string billJson = 3;</code>
   */
  com.google.protobuf.ByteString
      getBillJsonBytes();

  /**
   * <code>string billItemJson = 4;</code>
   */
  java.lang.String getBillItemJson();
  /**
   * <code>string billItemJson = 4;</code>
   */
  com.google.protobuf.ByteString
      getBillItemJsonBytes();

  /**
   * <code>string belongTenantId = 5;</code>
   */
  java.lang.String getBelongTenantId();
  /**
   * <code>string belongTenantId = 5;</code>
   */
  com.google.protobuf.ByteString
      getBelongTenantIdBytes();
}
