// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public final class Bill {
  private Bill() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_FlowTempTableOperateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_FlowTempTableOperateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_FlowTempTableOperateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_FlowTempTableOperateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BatchArrivalBillAutoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BatchArrivalBillAutoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityDeleteReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityDeleteReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_ListBillIdsGroupReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_ListBillIdsGroupReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityCreateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityCreateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillQueryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillQueryReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityCommonQueryFlowReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityCommonQueryFlowReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntitySqlQueryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntitySqlQueryReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillQueryUpdateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillQueryUpdateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillSerialNumberCheckReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillSerialNumberCheckReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillChangeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillChangeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CompareConditionsReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CompareConditionsReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CompareConditionsResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CompareConditionsResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_SaveBillReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_SaveBillReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_DeleteBillReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_DeleteBillReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BatchEditReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BatchEditReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommonCreateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommonCreateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_MethordExecReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_MethordExecReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_StatusTrackReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_StatusTrackReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommonEditReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommonEditReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityEditReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityEditReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommitOperateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommitOperateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommitOperateExeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommitOperateExeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillQueryResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillQueryResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityCommonQueryFlowResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityCommonQueryFlowResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntitySqlQueryResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntitySqlQueryResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillQueryUpdateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillQueryUpdateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillSerialNumberCheckResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillSerialNumberCheckResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BatchArrivalBillAutoResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BatchArrivalBillAutoResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_ListBillIdsGroupResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_ListBillIdsGroupResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BillChangeResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BillChangeResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_SaveBillResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_SaveBillResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_DeleteBillResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_DeleteBillResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_BatchEditResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_BatchEditResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_StatusTrackResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_StatusTrackResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommonCreateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommonCreateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_MethordExecResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_MethordExecResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommonEditResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommonEditResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityEditResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityEditResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityCreateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityCreateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_EntityDeleteResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_EntityDeleteResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommitOperateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommitOperateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_service_v1_CommitOperateExeResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_service_v1_CommitOperateExeResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbill.proto\022\017bill.service.v1\"\227\001\n\027FlowTe" +
      "mpTableOperateReq\022\026\n\016fromBillTypeId\030\001 \001(" +
      "\t\022\022\n\nbillTypeId\030\002 \001(\t\022\016\n\006billId\030\003 \001(\t\022\032\n" +
      "\022mapTempTalbeString\030\004 \001(\t\022\021\n\tisExecStr\030\005" +
      " \001(\t\022\021\n\tuserLogin\030\006 \001(\t\"\216\001\n\030FlowTempTabl" +
      "eOperateResp\022\027\n\017responseMessage\030\001 \001(\t\022\024\n" +
      "\014errorMessage\030\002 \001(\t\022\023\n\013infoMessage\030\003 \001(\t" +
      "\022\024\n\014currBillJson\030\004 \001(\t\022\030\n\020currBillItemJs" +
      "on\030\005 \001(\t\"m\n\027BatchArrivalBillAutoReq\022\023\n\013o" +
      "perateType\030\001 \001(\t\022\022\n\nbillTypeId\030\002 \001(\t\022\026\n\016" +
      "currBillIdsStr\030\003 \001(\t\022\021\n\tuserLogin\030\004 \001(\t\"" +
      "\236\001\n\017EntityDeleteReq\022\022\n\nbillTypeId\030\001 \001(\t\022" +
      "\020\n\010edStatus\030\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014b" +
      "illItemJson\030\004 \001(\t\022\026\n\016fromBillTypeId\030\005 \001(" +
      "\t\022\022\n\nmethodName\030\006 \001(\t\022\021\n\tuserLogin\030\007 \001(\t" +
      "\"i\n\023ListBillIdsGroupReq\022\023\n\013operateType\030\001" +
      " \001(\t\022\022\n\nbillTypeId\030\002 \001(\t\022\026\n\016listBillIdsS" +
      "tr\030\003 \001(\t\022\021\n\tuserLogin\030\004 \001(\t\"\236\001\n\017EntityCr" +
      "eateReq\022\022\n\nbillTypeId\030\001 \001(\t\022\020\n\010edStatus\030" +
      "\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014billItemJson\030" +
      "\004 \001(\t\022\026\n\016fromBillTypeId\030\005 \001(\t\022\022\n\nmethodN" +
      "ame\030\006 \001(\t\022\021\n\tuserLogin\030\007 \001(\t\"^\n\014BillQuer" +
      "yReq\022\022\n\nbillTypeId\030\001 \001(\t\022\016\n\006billId\030\002 \001(\t" +
      "\022\022\n\nddTenantId\030\003 \001(\t\022\026\n\016belongTenantId\030\004" +
      " \001(\t\"S\n\030EntityCommonQueryFlowReq\022\023\n\013enti" +
      "tyGroup\030\001 \001(\t\022\016\n\006strSql\030\002 \001(\t\022\022\n\nddTenan" +
      "tId\030\003 \001(\t\"L\n\021EntitySqlQueryReq\022\023\n\013entity" +
      "Group\030\001 \001(\t\022\016\n\006strSql\030\002 \001(\t\022\022\n\nddTenantI" +
      "d\030\003 \001(\t\"|\n\022BillQueryUpdateReq\022\022\n\nbillTyp" +
      "eId\030\001 \001(\t\022\022\n\nddTenantId\030\002 \001(\t\022\020\n\010billJso" +
      "n\030\003 \001(\t\022\024\n\014billItemJson\030\004 \001(\t\022\026\n\016belongT" +
      "enantId\030\005 \001(\t\"@\n\030BillSerialNumberCheckRe" +
      "q\022\022\n\nddTenantId\030\001 \001(\t\022\020\n\010billJson\030\002 \001(\t\"" +
      "\254\001\n\rBillChangeReq\022\022\n\nbillTypeId\030\001 \001(\t\022\020\n" +
      "\010edStatus\030\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014bil" +
      "lItemJson\030\004 \001(\t\022\026\n\016fromBillTypeId\030\005 \001(\t\022" +
      "\022\n\nmethodName\030\006 \001(\t\022\021\n\tuserLogin\030\007 \001(\t\022\016" +
      "\n\006billId\030\010 \001(\t\"\235\001\n\024CompareConditionsReq\022" +
      "\022\n\nconditions\030\001 \001(\t\022\022\n\nbillTypeId\030\002 \001(\t\022" +
      "\022\n\nddTenantId\030\003 \001(\t\022\020\n\010billJson\030\004 \001(\t\022\024\n" +
      "\014billItemJson\030\005 \001(\t\022\016\n\006billId\030\006 \001(\t\022\021\n\tu" +
      "serLogin\030\007 \001(\t\"A\n\025CompareConditionsResp\022" +
      "\020\n\010resultOk\030\001 \001(\t\022\026\n\016resultErrorMsg\030\002 \001(" +
      "\t\"n\n\013SaveBillReq\022\022\n\nbillTypeId\030\001 \001(\t\022\020\n\010" +
      "edStatus\030\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014bill" +
      "ItemJson\030\004 \001(\t\022\021\n\tuserLogin\030\005 \001(\t\"F\n\rDel" +
      "eteBillReq\022\022\n\nbillTypeId\030\001 \001(\t\022\016\n\006billId" +
      "\030\002 \001(\t\022\021\n\tuserLogin\030\003 \001(\t\"X\n\014BatchEditRe" +
      "q\022\022\n\nbillTypeId\030\001 \001(\t\022\017\n\007billIds\030\002 \001(\t\022\020" +
      "\n\010billJson\030\003 \001(\t\022\021\n\tuserLogin\030\004 \001(\t\"\256\001\n\017" +
      "CommonCreateReq\022\022\n\nbillTypeId\030\001 \001(\t\022\020\n\010e" +
      "dStatus\030\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014billI" +
      "temJson\030\004 \001(\t\022\026\n\016fromBillTypeId\030\005 \001(\t\022\022\n" +
      "\nmethodName\030\006 \001(\t\022\021\n\tuserLogin\030\007 \001(\t\022\016\n\006" +
      "billId\030\010 \001(\t\"\255\001\n\016MethordExecReq\022\022\n\nbillT" +
      "ypeId\030\001 \001(\t\022\020\n\010edStatus\030\002 \001(\t\022\020\n\010billJso" +
      "n\030\003 \001(\t\022\024\n\014billItemJson\030\004 \001(\t\022\026\n\016fromBil" +
      "lTypeId\030\005 \001(\t\022\022\n\nmethodName\030\006 \001(\t\022\021\n\tuse" +
      "rLogin\030\007 \001(\t\022\016\n\006billId\030\010 \001(\t\"\\\n\016StatusTr" +
      "ackReq\022\022\n\nbillTypeId\030\001 \001(\t\022\016\n\006billId\030\002 \001" +
      "(\t\022\023\n\013operateType\030\003 \001(\t\022\021\n\tuserLogin\030\004 \001" +
      "(\t\"\234\001\n\rCommonEditReq\022\022\n\nbillTypeId\030\001 \001(\t" +
      "\022\020\n\010edStatus\030\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014" +
      "billItemJson\030\004 \001(\t\022\026\n\016fromBillTypeId\030\005 \001" +
      "(\t\022\022\n\nmethodName\030\006 \001(\t\022\021\n\tuserLogin\030\007 \001(" +
      "\t\"\254\001\n\rEntityEditReq\022\022\n\nbillTypeId\030\001 \001(\t\022" +
      "\020\n\010edStatus\030\002 \001(\t\022\020\n\010billJson\030\003 \001(\t\022\024\n\014b" +
      "illItemJson\030\004 \001(\t\022\026\n\016fromBillTypeId\030\005 \001(" +
      "\t\022\022\n\nmethodName\030\006 \001(\t\022\021\n\tuserLogin\030\007 \001(\t" +
      "\022\016\n\006billId\030\010 \001(\t\"%\n\020CommitOperateReq\022\021\n\t" +
      "userLogin\030\001 \001(\t\"=\n\023CommitOperateExeReq\022\022" +
      "\n\nddTenantId\030\001 \001(\t\022\022\n\nsqlListStr\030\002 \001(\t\"\221" +
      "\001\n\rBillQueryResp\022\020\n\010billJson\030\001 \001(\t\022\024\n\014bi" +
      "llItemJson\030\002 \001(\t\022\024\n\014resultBillId\030\003 \001(\t\022\027" +
      "\n\017responseMessage\030\004 \001(\t\022\024\n\014errorMessage\030" +
      "\005 \001(\t\022\023\n\013infoMessage\030\006 \001(\t\"q\n\031EntityComm" +
      "onQueryFlowResp\022\020\n\010listJson\030\001 \001(\t\022\027\n\017res" +
      "ponseMessage\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t" +
      "\022\023\n\013infoMessage\030\004 \001(\t\"j\n\022EntitySqlQueryR" +
      "esp\022\020\n\010listJson\030\001 \001(\t\022\027\n\017responseMessage" +
      "\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\023\n\013infoMess" +
      "age\030\004 \001(\t\"\211\001\n\023BillQueryUpdateResp\022\024\n\014cur" +
      "rBillJson\030\001 \001(\t\022\030\n\020currBillItemJson\030\002 \001(" +
      "\t\022\027\n\017responseMessage\030\003 \001(\t\022\024\n\014errorMessa" +
      "ge\030\004 \001(\t\022\023\n\013infoMessage\030\005 \001(\t\".\n\031BillSer" +
      "ialNumberCheckResp\022\021\n\treturnStr\030\001 \001(\t\"\234\001" +
      "\n\030BatchArrivalBillAutoResp\022\020\n\010billJson\030\001" +
      " \001(\t\022\024\n\014billItemJson\030\002 \001(\t\022\024\n\014resultBill" +
      "Id\030\003 \001(\t\022\027\n\017responseMessage\030\004 \001(\t\022\024\n\014err" +
      "orMessage\030\005 \001(\t\022\023\n\013infoMessage\030\006 \001(\t\"q\n\024" +
      "ListBillIdsGroupResp\022\025\n\rresultListStr\030\001 " +
      "\001(\t\022\027\n\017responseMessage\030\002 \001(\t\022\024\n\014errorMes" +
      "sage\030\003 \001(\t\022\023\n\013infoMessage\030\004 \001(\t\"j\n\016BillC" +
      "hangeResp\022\024\n\014resultBillId\030\001 \001(\t\022\027\n\017respo" +
      "nseMessage\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\023" +
      "\n\013infoMessage\030\004 \001(\t\"\261\001\n\014SaveBillResp\022\024\n\014" +
      "resultBillId\030\001 \001(\t\022\027\n\017responseMessage\030\002 " +
      "\001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\023\n\013infoMessage" +
      "\030\004 \001(\t\022\024\n\014currBillJson\030\005 \001(\t\022\030\n\020currBill" +
      "ItemJson\030\006 \001(\t\022\027\n\017mapTempTableStr\030\007 \001(\t\"" +
      "j\n\016DeleteBillResp\022\024\n\014resultBillId\030\001 \001(\t\022" +
      "\027\n\017responseMessage\030\002 \001(\t\022\024\n\014errorMessage" +
      "\030\003 \001(\t\022\023\n\013infoMessage\030\004 \001(\t\"i\n\rBatchEdit" +
      "Resp\022\024\n\014resultBillId\030\001 \001(\t\022\027\n\017responseMe" +
      "ssage\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\023\n\013inf" +
      "oMessage\030\004 \001(\t\"k\n\017StatusTrackResp\022\024\n\014res" +
      "ultBillId\030\001 \001(\t\022\027\n\017responseMessage\030\002 \001(\t" +
      "\022\024\n\014errorMessage\030\003 \001(\t\022\023\n\013infoMessage\030\004 " +
      "\001(\t\"l\n\020CommonCreateResp\022\024\n\014resultBillId\030" +
      "\001 \001(\t\022\027\n\017responseMessage\030\002 \001(\t\022\024\n\014errorM" +
      "essage\030\003 \001(\t\022\023\n\013infoMessage\030\004 \001(\t\"k\n\017Met" +
      "hordExecResp\022\024\n\014resultBillId\030\001 \001(\t\022\027\n\017re" +
      "sponseMessage\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(" +
      "\t\022\023\n\013infoMessage\030\004 \001(\t\"j\n\016CommonEditResp" +
      "\022\024\n\014resultBillId\030\001 \001(\t\022\027\n\017responseMessag" +
      "e\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\023\n\013infoMes" +
      "sage\030\004 \001(\t\"j\n\016EntityEditResp\022\024\n\014resultBi" +
      "llId\030\001 \001(\t\022\027\n\017responseMessage\030\002 \001(\t\022\024\n\014e" +
      "rrorMessage\030\003 \001(\t\022\023\n\013infoMessage\030\004 \001(\t\"l" +
      "\n\020EntityCreateResp\022\024\n\014resultBillId\030\001 \001(\t" +
      "\022\027\n\017responseMessage\030\002 \001(\t\022\024\n\014errorMessag" +
      "e\030\003 \001(\t\022\023\n\013infoMessage\030\004 \001(\t\"l\n\020EntityDe" +
      "leteResp\022\024\n\014resultBillId\030\001 \001(\t\022\027\n\017respon" +
      "seMessage\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\023\n" +
      "\013infoMessage\030\004 \001(\t\"B\n\021CommitOperateResp\022" +
      "\027\n\017responseMessage\030\001 \001(\t\022\024\n\014errorMessage" +
      "\030\002 \001(\t\"E\n\024CommitOperateExeResp\022\027\n\017respon" +
      "seMessage\030\001 \001(\t\022\024\n\014errorMessage\030\002 \001(\t2\340\017" +
      "\n\004bill\022O\n\020commonSaveBillV2\022\034.bill.servic" +
      "e.v1.SaveBillReq\032\035.bill.service.v1.SaveB" +
      "illResp\022U\n\022commonDeleteBillV2\022\036.bill.ser" +
      "vice.v1.DeleteBillReq\032\037.bill.service.v1." +
      "DeleteBillResp\022J\n\tBatchEdit\022\035.bill.servi" +
      "ce.v1.BatchEditReq\032\036.bill.service.v1.Bat" +
      "chEditResp\022U\n\020commonSaveStatus\022\037.bill.se" +
      "rvice.v1.StatusTrackReq\032 .bill.service.v" +
      "1.StatusTrackResp\022]\n\026commonCreateBillByB" +
      "ill\022 .bill.service.v1.CommonCreateReq\032!." +
      "bill.service.v1.CommonCreateResp\022W\n\024comm" +
      "onEditBillByBill\022\036.bill.service.v1.Commo" +
      "nEditReq\032\037.bill.service.v1.CommonEditRes" +
      "p\022M\n\nentityEdit\022\036.bill.service.v1.Entity" +
      "EditReq\032\037.bill.service.v1.EntityEditResp" +
      "\022S\n\014entityCreate\022 .bill.service.v1.Entit" +
      "yCreateReq\032!.bill.service.v1.EntityCreat" +
      "eResp\022S\n\014entityDelete\022 .bill.service.v1." +
      "EntityDeleteReq\032!.bill.service.v1.Entity" +
      "DeleteResp\022V\n\rcommitOperate\022!.bill.servi" +
      "ce.v1.CommitOperateReq\032\".bill.service.v1" +
      ".CommitOperateResp\022b\n\021compareConditions\022" +
      "%.bill.service.v1.CompareConditionsReq\032&" +
      ".bill.service.v1.CompareConditionsResp\022M" +
      "\n\nbillChange\022\036.bill.service.v1.BillChang" +
      "eReq\032\037.bill.service.v1.BillChangeResp\022J\n" +
      "\tbillQuery\022\035.bill.service.v1.BillQueryRe" +
      "q\032\036.bill.service.v1.BillQueryResp\022Y\n\016ent" +
      "itySqlQuery\022\".bill.service.v1.EntitySqlQ" +
      "ueryReq\032#.bill.service.v1.EntitySqlQuery" +
      "Resp\022k\n\024batchArrivalBillAuto\022(.bill.serv" +
      "ice.v1.BatchArrivalBillAutoReq\032).bill.se" +
      "rvice.v1.BatchArrivalBillAutoResp\022k\n\024flo" +
      "wTempTableOperate\022(.bill.service.v1.Flow" +
      "TempTableOperateReq\032).bill.service.v1.Fl" +
      "owTempTableOperateResp\022_\n\020listBillIdsGro" +
      "up\022$.bill.service.v1.ListBillIdsGroupReq" +
      "\032%.bill.service.v1.ListBillIdsGroupResp\022" +
      "\\\n\017billQueryUpdate\022#.bill.service.v1.Bil" +
      "lQueryUpdateReq\032$.bill.service.v1.BillQu" +
      "eryUpdateResp\022n\n\025billSerialNumberCheck\022)" +
      ".bill.service.v1.BillSerialNumberCheckRe" +
      "q\032*.bill.service.v1.BillSerialNumberChec" +
      "kResp\022P\n\013methordExec\022\037.bill.service.v1.M" +
      "ethordExecReq\032 .bill.service.v1.MethordE" +
      "xecResp\022n\n\025entityCommonQueryFlow\022).bill." +
      "service.v1.EntityCommonQueryFlowReq\032*.bi" +
      "ll.service.v1.EntityCommonQueryFlowResp\022" +
      "_\n\020commitOperateExe\022$.bill.service.v1.Co" +
      "mmitOperateExeReq\032%.bill.service.v1.Comm" +
      "itOperateExeRespB\021P\001Z\r./api/bill/v1b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bill_service_v1_FlowTempTableOperateReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bill_service_v1_FlowTempTableOperateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_FlowTempTableOperateReq_descriptor,
        new java.lang.String[] { "FromBillTypeId", "BillTypeId", "BillId", "MapTempTalbeString", "IsExecStr", "UserLogin", });
    internal_static_bill_service_v1_FlowTempTableOperateResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bill_service_v1_FlowTempTableOperateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_FlowTempTableOperateResp_descriptor,
        new java.lang.String[] { "ResponseMessage", "ErrorMessage", "InfoMessage", "CurrBillJson", "CurrBillItemJson", });
    internal_static_bill_service_v1_BatchArrivalBillAutoReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bill_service_v1_BatchArrivalBillAutoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BatchArrivalBillAutoReq_descriptor,
        new java.lang.String[] { "OperateType", "BillTypeId", "CurrBillIdsStr", "UserLogin", });
    internal_static_bill_service_v1_EntityDeleteReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bill_service_v1_EntityDeleteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityDeleteReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", });
    internal_static_bill_service_v1_ListBillIdsGroupReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bill_service_v1_ListBillIdsGroupReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_ListBillIdsGroupReq_descriptor,
        new java.lang.String[] { "OperateType", "BillTypeId", "ListBillIdsStr", "UserLogin", });
    internal_static_bill_service_v1_EntityCreateReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bill_service_v1_EntityCreateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityCreateReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", });
    internal_static_bill_service_v1_BillQueryReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_bill_service_v1_BillQueryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillQueryReq_descriptor,
        new java.lang.String[] { "BillTypeId", "BillId", "DdTenantId", "BelongTenantId", });
    internal_static_bill_service_v1_EntityCommonQueryFlowReq_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_bill_service_v1_EntityCommonQueryFlowReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityCommonQueryFlowReq_descriptor,
        new java.lang.String[] { "EntityGroup", "StrSql", "DdTenantId", });
    internal_static_bill_service_v1_EntitySqlQueryReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_bill_service_v1_EntitySqlQueryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntitySqlQueryReq_descriptor,
        new java.lang.String[] { "EntityGroup", "StrSql", "DdTenantId", });
    internal_static_bill_service_v1_BillQueryUpdateReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_bill_service_v1_BillQueryUpdateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillQueryUpdateReq_descriptor,
        new java.lang.String[] { "BillTypeId", "DdTenantId", "BillJson", "BillItemJson", "BelongTenantId", });
    internal_static_bill_service_v1_BillSerialNumberCheckReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_bill_service_v1_BillSerialNumberCheckReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillSerialNumberCheckReq_descriptor,
        new java.lang.String[] { "DdTenantId", "BillJson", });
    internal_static_bill_service_v1_BillChangeReq_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_bill_service_v1_BillChangeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillChangeReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", "BillId", });
    internal_static_bill_service_v1_CompareConditionsReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_bill_service_v1_CompareConditionsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CompareConditionsReq_descriptor,
        new java.lang.String[] { "Conditions", "BillTypeId", "DdTenantId", "BillJson", "BillItemJson", "BillId", "UserLogin", });
    internal_static_bill_service_v1_CompareConditionsResp_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_bill_service_v1_CompareConditionsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CompareConditionsResp_descriptor,
        new java.lang.String[] { "ResultOk", "ResultErrorMsg", });
    internal_static_bill_service_v1_SaveBillReq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_bill_service_v1_SaveBillReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_SaveBillReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "UserLogin", });
    internal_static_bill_service_v1_DeleteBillReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_bill_service_v1_DeleteBillReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_DeleteBillReq_descriptor,
        new java.lang.String[] { "BillTypeId", "BillId", "UserLogin", });
    internal_static_bill_service_v1_BatchEditReq_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_bill_service_v1_BatchEditReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BatchEditReq_descriptor,
        new java.lang.String[] { "BillTypeId", "BillIds", "BillJson", "UserLogin", });
    internal_static_bill_service_v1_CommonCreateReq_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_bill_service_v1_CommonCreateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommonCreateReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", "BillId", });
    internal_static_bill_service_v1_MethordExecReq_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_bill_service_v1_MethordExecReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_MethordExecReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", "BillId", });
    internal_static_bill_service_v1_StatusTrackReq_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_bill_service_v1_StatusTrackReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_StatusTrackReq_descriptor,
        new java.lang.String[] { "BillTypeId", "BillId", "OperateType", "UserLogin", });
    internal_static_bill_service_v1_CommonEditReq_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_bill_service_v1_CommonEditReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommonEditReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", });
    internal_static_bill_service_v1_EntityEditReq_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_bill_service_v1_EntityEditReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityEditReq_descriptor,
        new java.lang.String[] { "BillTypeId", "EdStatus", "BillJson", "BillItemJson", "FromBillTypeId", "MethodName", "UserLogin", "BillId", });
    internal_static_bill_service_v1_CommitOperateReq_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_bill_service_v1_CommitOperateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommitOperateReq_descriptor,
        new java.lang.String[] { "UserLogin", });
    internal_static_bill_service_v1_CommitOperateExeReq_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_bill_service_v1_CommitOperateExeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommitOperateExeReq_descriptor,
        new java.lang.String[] { "DdTenantId", "SqlListStr", });
    internal_static_bill_service_v1_BillQueryResp_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_bill_service_v1_BillQueryResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillQueryResp_descriptor,
        new java.lang.String[] { "BillJson", "BillItemJson", "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_EntityCommonQueryFlowResp_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_bill_service_v1_EntityCommonQueryFlowResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityCommonQueryFlowResp_descriptor,
        new java.lang.String[] { "ListJson", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_EntitySqlQueryResp_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_bill_service_v1_EntitySqlQueryResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntitySqlQueryResp_descriptor,
        new java.lang.String[] { "ListJson", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_BillQueryUpdateResp_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_bill_service_v1_BillQueryUpdateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillQueryUpdateResp_descriptor,
        new java.lang.String[] { "CurrBillJson", "CurrBillItemJson", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_BillSerialNumberCheckResp_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_bill_service_v1_BillSerialNumberCheckResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillSerialNumberCheckResp_descriptor,
        new java.lang.String[] { "ReturnStr", });
    internal_static_bill_service_v1_BatchArrivalBillAutoResp_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_bill_service_v1_BatchArrivalBillAutoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BatchArrivalBillAutoResp_descriptor,
        new java.lang.String[] { "BillJson", "BillItemJson", "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_ListBillIdsGroupResp_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_bill_service_v1_ListBillIdsGroupResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_ListBillIdsGroupResp_descriptor,
        new java.lang.String[] { "ResultListStr", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_BillChangeResp_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_bill_service_v1_BillChangeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BillChangeResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_SaveBillResp_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_bill_service_v1_SaveBillResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_SaveBillResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", "CurrBillJson", "CurrBillItemJson", "MapTempTableStr", });
    internal_static_bill_service_v1_DeleteBillResp_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_bill_service_v1_DeleteBillResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_DeleteBillResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_BatchEditResp_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_bill_service_v1_BatchEditResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_BatchEditResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_StatusTrackResp_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_bill_service_v1_StatusTrackResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_StatusTrackResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_CommonCreateResp_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_bill_service_v1_CommonCreateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommonCreateResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_MethordExecResp_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_bill_service_v1_MethordExecResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_MethordExecResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_CommonEditResp_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_bill_service_v1_CommonEditResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommonEditResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_EntityEditResp_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_bill_service_v1_EntityEditResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityEditResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_EntityCreateResp_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_bill_service_v1_EntityCreateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityCreateResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_EntityDeleteResp_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_bill_service_v1_EntityDeleteResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_EntityDeleteResp_descriptor,
        new java.lang.String[] { "ResultBillId", "ResponseMessage", "ErrorMessage", "InfoMessage", });
    internal_static_bill_service_v1_CommitOperateResp_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_bill_service_v1_CommitOperateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommitOperateResp_descriptor,
        new java.lang.String[] { "ResponseMessage", "ErrorMessage", });
    internal_static_bill_service_v1_CommitOperateExeResp_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_bill_service_v1_CommitOperateExeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_service_v1_CommitOperateExeResp_descriptor,
        new java.lang.String[] { "ResponseMessage", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
