// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface BillSerialNumberCheckReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.BillSerialNumberCheckReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ddTenantId = 1;</code>
   */
  java.lang.String getDdTenantId();
  /**
   * <code>string ddTenantId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDdTenantIdBytes();

  /**
   * <code>string billJson = 2;</code>
   */
  java.lang.String getBillJson();
  /**
   * <code>string billJson = 2;</code>
   */
  com.google.protobuf.ByteString
      getBillJsonBytes();
}
