// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface CommitOperateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.CommitOperateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 1;</code>
   */
  java.lang.String getUserLogin();
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserLoginBytes();
}
