// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

/**
 * Protobuf type {@code bill.service.v1.CommitOperateExeReq}
 */
public  final class CommitOperateExeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bill.service.v1.CommitOperateExeReq)
    CommitOperateExeReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommitOperateExeReq.newBuilder() to construct.
  private CommitOperateExeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommitOperateExeReq() {
    ddTenantId_ = "";
    sqlListStr_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommitOperateExeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ddTenantId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sqlListStr_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bill.service.v1.Bill.internal_static_bill_service_v1_CommitOperateExeReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bill.service.v1.Bill.internal_static_bill_service_v1_CommitOperateExeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bill.service.v1.CommitOperateExeReq.class, bill.service.v1.CommitOperateExeReq.Builder.class);
  }

  public static final int DDTENANTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object ddTenantId_;
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string ddTenantId = 1;</code>
   */
  public java.lang.String getDdTenantId() {
    java.lang.Object ref = ddTenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ddTenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string ddTenantId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDdTenantIdBytes() {
    java.lang.Object ref = ddTenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ddTenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SQLLISTSTR_FIELD_NUMBER = 2;
  private volatile java.lang.Object sqlListStr_;
  /**
   * <code>string sqlListStr = 2;</code>
   */
  public java.lang.String getSqlListStr() {
    java.lang.Object ref = sqlListStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sqlListStr_ = s;
      return s;
    }
  }
  /**
   * <code>string sqlListStr = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSqlListStrBytes() {
    java.lang.Object ref = sqlListStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sqlListStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDdTenantIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ddTenantId_);
    }
    if (!getSqlListStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sqlListStr_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDdTenantIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ddTenantId_);
    }
    if (!getSqlListStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sqlListStr_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bill.service.v1.CommitOperateExeReq)) {
      return super.equals(obj);
    }
    bill.service.v1.CommitOperateExeReq other = (bill.service.v1.CommitOperateExeReq) obj;

    boolean result = true;
    result = result && getDdTenantId()
        .equals(other.getDdTenantId());
    result = result && getSqlListStr()
        .equals(other.getSqlListStr());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DDTENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getDdTenantId().hashCode();
    hash = (37 * hash) + SQLLISTSTR_FIELD_NUMBER;
    hash = (53 * hash) + getSqlListStr().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bill.service.v1.CommitOperateExeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bill.service.v1.CommitOperateExeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bill.service.v1.CommitOperateExeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bill.service.v1.CommitOperateExeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bill.service.v1.CommitOperateExeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bill.service.v1.CommitOperateExeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bill.service.v1.CommitOperateExeReq)
      bill.service.v1.CommitOperateExeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_CommitOperateExeReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_CommitOperateExeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bill.service.v1.CommitOperateExeReq.class, bill.service.v1.CommitOperateExeReq.Builder.class);
    }

    // Construct using bill.service.v1.CommitOperateExeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ddTenantId_ = "";

      sqlListStr_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_CommitOperateExeReq_descriptor;
    }

    public bill.service.v1.CommitOperateExeReq getDefaultInstanceForType() {
      return bill.service.v1.CommitOperateExeReq.getDefaultInstance();
    }

    public bill.service.v1.CommitOperateExeReq build() {
      bill.service.v1.CommitOperateExeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bill.service.v1.CommitOperateExeReq buildPartial() {
      bill.service.v1.CommitOperateExeReq result = new bill.service.v1.CommitOperateExeReq(this);
      result.ddTenantId_ = ddTenantId_;
      result.sqlListStr_ = sqlListStr_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bill.service.v1.CommitOperateExeReq) {
        return mergeFrom((bill.service.v1.CommitOperateExeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bill.service.v1.CommitOperateExeReq other) {
      if (other == bill.service.v1.CommitOperateExeReq.getDefaultInstance()) return this;
      if (!other.getDdTenantId().isEmpty()) {
        ddTenantId_ = other.ddTenantId_;
        onChanged();
      }
      if (!other.getSqlListStr().isEmpty()) {
        sqlListStr_ = other.sqlListStr_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bill.service.v1.CommitOperateExeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bill.service.v1.CommitOperateExeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ddTenantId_ = "";
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string ddTenantId = 1;</code>
     */
    public java.lang.String getDdTenantId() {
      java.lang.Object ref = ddTenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ddTenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string ddTenantId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDdTenantIdBytes() {
      java.lang.Object ref = ddTenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ddTenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string ddTenantId = 1;</code>
     */
    public Builder setDdTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ddTenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string ddTenantId = 1;</code>
     */
    public Builder clearDdTenantId() {
      
      ddTenantId_ = getDefaultInstance().getDdTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string ddTenantId = 1;</code>
     */
    public Builder setDdTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ddTenantId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sqlListStr_ = "";
    /**
     * <code>string sqlListStr = 2;</code>
     */
    public java.lang.String getSqlListStr() {
      java.lang.Object ref = sqlListStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlListStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sqlListStr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSqlListStrBytes() {
      java.lang.Object ref = sqlListStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlListStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sqlListStr = 2;</code>
     */
    public Builder setSqlListStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sqlListStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sqlListStr = 2;</code>
     */
    public Builder clearSqlListStr() {
      
      sqlListStr_ = getDefaultInstance().getSqlListStr();
      onChanged();
      return this;
    }
    /**
     * <code>string sqlListStr = 2;</code>
     */
    public Builder setSqlListStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sqlListStr_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bill.service.v1.CommitOperateExeReq)
  }

  // @@protoc_insertion_point(class_scope:bill.service.v1.CommitOperateExeReq)
  private static final bill.service.v1.CommitOperateExeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bill.service.v1.CommitOperateExeReq();
  }

  public static bill.service.v1.CommitOperateExeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommitOperateExeReq>
      PARSER = new com.google.protobuf.AbstractParser<CommitOperateExeReq>() {
    public CommitOperateExeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommitOperateExeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommitOperateExeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommitOperateExeReq> getParserForType() {
    return PARSER;
  }

  public bill.service.v1.CommitOperateExeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

