// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface CompareConditionsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.CompareConditionsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resultOk = 1;</code>
   */
  java.lang.String getResultOk();
  /**
   * <code>string resultOk = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultOkBytes();

  /**
   * <code>string resultErrorMsg = 2;</code>
   */
  java.lang.String getResultErrorMsg();
  /**
   * <code>string resultErrorMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultErrorMsgBytes();
}
