// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface EntitySqlQueryRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.EntitySqlQueryResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string listJson = 1;</code>
   */
  java.lang.String getListJson();
  /**
   * <code>string listJson = 1;</code>
   */
  com.google.protobuf.ByteString
      getListJsonBytes();

  /**
   * <code>string responseMessage = 2;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>string errorMessage = 3;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>string infoMessage = 4;</code>
   */
  java.lang.String getInfoMessage();
  /**
   * <code>string infoMessage = 4;</code>
   */
  com.google.protobuf.ByteString
      getInfoMessageBytes();
}
