// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface FlowTempTableOperateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.FlowTempTableOperateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromBillTypeId = 1;</code>
   */
  java.lang.String getFromBillTypeId();
  /**
   * <code>string fromBillTypeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromBillTypeIdBytes();

  /**
   * <code>string billTypeId = 2;</code>
   */
  java.lang.String getBillTypeId();
  /**
   * <code>string billTypeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getBillTypeIdBytes();

  /**
   * <code>string billId = 3;</code>
   */
  java.lang.String getBillId();
  /**
   * <code>string billId = 3;</code>
   */
  com.google.protobuf.ByteString
      getBillIdBytes();

  /**
   * <code>string mapTempTalbeString = 4;</code>
   */
  java.lang.String getMapTempTalbeString();
  /**
   * <code>string mapTempTalbeString = 4;</code>
   */
  com.google.protobuf.ByteString
      getMapTempTalbeStringBytes();

  /**
   * <code>string isExecStr = 5;</code>
   */
  java.lang.String getIsExecStr();
  /**
   * <code>string isExecStr = 5;</code>
   */
  com.google.protobuf.ByteString
      getIsExecStrBytes();

  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 6;</code>
   */
  java.lang.String getUserLogin();
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 6;</code>
   */
  com.google.protobuf.ByteString
      getUserLoginBytes();
}
