// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface FlowTempTableOperateRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.FlowTempTableOperateResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>string infoMessage = 3;</code>
   */
  java.lang.String getInfoMessage();
  /**
   * <code>string infoMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getInfoMessageBytes();

  /**
   * <code>string currBillJson = 4;</code>
   */
  java.lang.String getCurrBillJson();
  /**
   * <code>string currBillJson = 4;</code>
   */
  com.google.protobuf.ByteString
      getCurrBillJsonBytes();

  /**
   * <code>string currBillItemJson = 5;</code>
   */
  java.lang.String getCurrBillItemJson();
  /**
   * <code>string currBillItemJson = 5;</code>
   */
  com.google.protobuf.ByteString
      getCurrBillItemJsonBytes();
}
