// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

/**
 * Protobuf type {@code bill.service.v1.FlowTempTableOperateReq}
 */
public  final class FlowTempTableOperateReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bill.service.v1.FlowTempTableOperateReq)
    FlowTempTableOperateReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlowTempTableOperateReq.newBuilder() to construct.
  private FlowTempTableOperateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlowTempTableOperateReq() {
    fromBillTypeId_ = "";
    billTypeId_ = "";
    billId_ = "";
    mapTempTalbeString_ = "";
    isExecStr_ = "";
    userLogin_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FlowTempTableOperateReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fromBillTypeId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            billTypeId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            billId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            mapTempTalbeString_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            isExecStr_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            userLogin_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bill.service.v1.Bill.internal_static_bill_service_v1_FlowTempTableOperateReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bill.service.v1.Bill.internal_static_bill_service_v1_FlowTempTableOperateReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bill.service.v1.FlowTempTableOperateReq.class, bill.service.v1.FlowTempTableOperateReq.Builder.class);
  }

  public static final int FROMBILLTYPEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object fromBillTypeId_;
  /**
   * <code>string fromBillTypeId = 1;</code>
   */
  public java.lang.String getFromBillTypeId() {
    java.lang.Object ref = fromBillTypeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromBillTypeId_ = s;
      return s;
    }
  }
  /**
   * <code>string fromBillTypeId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFromBillTypeIdBytes() {
    java.lang.Object ref = fromBillTypeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromBillTypeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BILLTYPEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object billTypeId_;
  /**
   * <code>string billTypeId = 2;</code>
   */
  public java.lang.String getBillTypeId() {
    java.lang.Object ref = billTypeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      billTypeId_ = s;
      return s;
    }
  }
  /**
   * <code>string billTypeId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBillTypeIdBytes() {
    java.lang.Object ref = billTypeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      billTypeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BILLID_FIELD_NUMBER = 3;
  private volatile java.lang.Object billId_;
  /**
   * <code>string billId = 3;</code>
   */
  public java.lang.String getBillId() {
    java.lang.Object ref = billId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      billId_ = s;
      return s;
    }
  }
  /**
   * <code>string billId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBillIdBytes() {
    java.lang.Object ref = billId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      billId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAPTEMPTALBESTRING_FIELD_NUMBER = 4;
  private volatile java.lang.Object mapTempTalbeString_;
  /**
   * <code>string mapTempTalbeString = 4;</code>
   */
  public java.lang.String getMapTempTalbeString() {
    java.lang.Object ref = mapTempTalbeString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mapTempTalbeString_ = s;
      return s;
    }
  }
  /**
   * <code>string mapTempTalbeString = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMapTempTalbeStringBytes() {
    java.lang.Object ref = mapTempTalbeString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mapTempTalbeString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISEXECSTR_FIELD_NUMBER = 5;
  private volatile java.lang.Object isExecStr_;
  /**
   * <code>string isExecStr = 5;</code>
   */
  public java.lang.String getIsExecStr() {
    java.lang.Object ref = isExecStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isExecStr_ = s;
      return s;
    }
  }
  /**
   * <code>string isExecStr = 5;</code>
   */
  public com.google.protobuf.ByteString
      getIsExecStrBytes() {
    java.lang.Object ref = isExecStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isExecStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERLOGIN_FIELD_NUMBER = 6;
  private volatile java.lang.Object userLogin_;
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 6;</code>
   */
  public java.lang.String getUserLogin() {
    java.lang.Object ref = userLogin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userLogin_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserLoginBytes() {
    java.lang.Object ref = userLogin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userLogin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFromBillTypeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromBillTypeId_);
    }
    if (!getBillTypeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, billTypeId_);
    }
    if (!getBillIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, billId_);
    }
    if (!getMapTempTalbeStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mapTempTalbeString_);
    }
    if (!getIsExecStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, isExecStr_);
    }
    if (!getUserLoginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userLogin_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFromBillTypeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromBillTypeId_);
    }
    if (!getBillTypeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, billTypeId_);
    }
    if (!getBillIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, billId_);
    }
    if (!getMapTempTalbeStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mapTempTalbeString_);
    }
    if (!getIsExecStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, isExecStr_);
    }
    if (!getUserLoginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userLogin_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bill.service.v1.FlowTempTableOperateReq)) {
      return super.equals(obj);
    }
    bill.service.v1.FlowTempTableOperateReq other = (bill.service.v1.FlowTempTableOperateReq) obj;

    boolean result = true;
    result = result && getFromBillTypeId()
        .equals(other.getFromBillTypeId());
    result = result && getBillTypeId()
        .equals(other.getBillTypeId());
    result = result && getBillId()
        .equals(other.getBillId());
    result = result && getMapTempTalbeString()
        .equals(other.getMapTempTalbeString());
    result = result && getIsExecStr()
        .equals(other.getIsExecStr());
    result = result && getUserLogin()
        .equals(other.getUserLogin());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROMBILLTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + getFromBillTypeId().hashCode();
    hash = (37 * hash) + BILLTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + getBillTypeId().hashCode();
    hash = (37 * hash) + BILLID_FIELD_NUMBER;
    hash = (53 * hash) + getBillId().hashCode();
    hash = (37 * hash) + MAPTEMPTALBESTRING_FIELD_NUMBER;
    hash = (53 * hash) + getMapTempTalbeString().hashCode();
    hash = (37 * hash) + ISEXECSTR_FIELD_NUMBER;
    hash = (53 * hash) + getIsExecStr().hashCode();
    hash = (37 * hash) + USERLOGIN_FIELD_NUMBER;
    hash = (53 * hash) + getUserLogin().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bill.service.v1.FlowTempTableOperateReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bill.service.v1.FlowTempTableOperateReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bill.service.v1.FlowTempTableOperateReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bill.service.v1.FlowTempTableOperateReq)
      bill.service.v1.FlowTempTableOperateReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_FlowTempTableOperateReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_FlowTempTableOperateReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bill.service.v1.FlowTempTableOperateReq.class, bill.service.v1.FlowTempTableOperateReq.Builder.class);
    }

    // Construct using bill.service.v1.FlowTempTableOperateReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      fromBillTypeId_ = "";

      billTypeId_ = "";

      billId_ = "";

      mapTempTalbeString_ = "";

      isExecStr_ = "";

      userLogin_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bill.service.v1.Bill.internal_static_bill_service_v1_FlowTempTableOperateReq_descriptor;
    }

    public bill.service.v1.FlowTempTableOperateReq getDefaultInstanceForType() {
      return bill.service.v1.FlowTempTableOperateReq.getDefaultInstance();
    }

    public bill.service.v1.FlowTempTableOperateReq build() {
      bill.service.v1.FlowTempTableOperateReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bill.service.v1.FlowTempTableOperateReq buildPartial() {
      bill.service.v1.FlowTempTableOperateReq result = new bill.service.v1.FlowTempTableOperateReq(this);
      result.fromBillTypeId_ = fromBillTypeId_;
      result.billTypeId_ = billTypeId_;
      result.billId_ = billId_;
      result.mapTempTalbeString_ = mapTempTalbeString_;
      result.isExecStr_ = isExecStr_;
      result.userLogin_ = userLogin_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bill.service.v1.FlowTempTableOperateReq) {
        return mergeFrom((bill.service.v1.FlowTempTableOperateReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bill.service.v1.FlowTempTableOperateReq other) {
      if (other == bill.service.v1.FlowTempTableOperateReq.getDefaultInstance()) return this;
      if (!other.getFromBillTypeId().isEmpty()) {
        fromBillTypeId_ = other.fromBillTypeId_;
        onChanged();
      }
      if (!other.getBillTypeId().isEmpty()) {
        billTypeId_ = other.billTypeId_;
        onChanged();
      }
      if (!other.getBillId().isEmpty()) {
        billId_ = other.billId_;
        onChanged();
      }
      if (!other.getMapTempTalbeString().isEmpty()) {
        mapTempTalbeString_ = other.mapTempTalbeString_;
        onChanged();
      }
      if (!other.getIsExecStr().isEmpty()) {
        isExecStr_ = other.isExecStr_;
        onChanged();
      }
      if (!other.getUserLogin().isEmpty()) {
        userLogin_ = other.userLogin_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bill.service.v1.FlowTempTableOperateReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bill.service.v1.FlowTempTableOperateReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fromBillTypeId_ = "";
    /**
     * <code>string fromBillTypeId = 1;</code>
     */
    public java.lang.String getFromBillTypeId() {
      java.lang.Object ref = fromBillTypeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromBillTypeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fromBillTypeId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromBillTypeIdBytes() {
      java.lang.Object ref = fromBillTypeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromBillTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fromBillTypeId = 1;</code>
     */
    public Builder setFromBillTypeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromBillTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fromBillTypeId = 1;</code>
     */
    public Builder clearFromBillTypeId() {
      
      fromBillTypeId_ = getDefaultInstance().getFromBillTypeId();
      onChanged();
      return this;
    }
    /**
     * <code>string fromBillTypeId = 1;</code>
     */
    public Builder setFromBillTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromBillTypeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object billTypeId_ = "";
    /**
     * <code>string billTypeId = 2;</code>
     */
    public java.lang.String getBillTypeId() {
      java.lang.Object ref = billTypeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billTypeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBillTypeIdBytes() {
      java.lang.Object ref = billTypeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public Builder setBillTypeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      billTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public Builder clearBillTypeId() {
      
      billTypeId_ = getDefaultInstance().getBillTypeId();
      onChanged();
      return this;
    }
    /**
     * <code>string billTypeId = 2;</code>
     */
    public Builder setBillTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      billTypeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object billId_ = "";
    /**
     * <code>string billId = 3;</code>
     */
    public java.lang.String getBillId() {
      java.lang.Object ref = billId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string billId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBillIdBytes() {
      java.lang.Object ref = billId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string billId = 3;</code>
     */
    public Builder setBillId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      billId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string billId = 3;</code>
     */
    public Builder clearBillId() {
      
      billId_ = getDefaultInstance().getBillId();
      onChanged();
      return this;
    }
    /**
     * <code>string billId = 3;</code>
     */
    public Builder setBillIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      billId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mapTempTalbeString_ = "";
    /**
     * <code>string mapTempTalbeString = 4;</code>
     */
    public java.lang.String getMapTempTalbeString() {
      java.lang.Object ref = mapTempTalbeString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mapTempTalbeString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mapTempTalbeString = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMapTempTalbeStringBytes() {
      java.lang.Object ref = mapTempTalbeString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mapTempTalbeString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mapTempTalbeString = 4;</code>
     */
    public Builder setMapTempTalbeString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mapTempTalbeString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mapTempTalbeString = 4;</code>
     */
    public Builder clearMapTempTalbeString() {
      
      mapTempTalbeString_ = getDefaultInstance().getMapTempTalbeString();
      onChanged();
      return this;
    }
    /**
     * <code>string mapTempTalbeString = 4;</code>
     */
    public Builder setMapTempTalbeStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mapTempTalbeString_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object isExecStr_ = "";
    /**
     * <code>string isExecStr = 5;</code>
     */
    public java.lang.String getIsExecStr() {
      java.lang.Object ref = isExecStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isExecStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isExecStr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIsExecStrBytes() {
      java.lang.Object ref = isExecStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isExecStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isExecStr = 5;</code>
     */
    public Builder setIsExecStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      isExecStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string isExecStr = 5;</code>
     */
    public Builder clearIsExecStr() {
      
      isExecStr_ = getDefaultInstance().getIsExecStr();
      onChanged();
      return this;
    }
    /**
     * <code>string isExecStr = 5;</code>
     */
    public Builder setIsExecStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      isExecStr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userLogin_ = "";
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string userLogin = 6;</code>
     */
    public java.lang.String getUserLogin() {
      java.lang.Object ref = userLogin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLogin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string userLogin = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserLoginBytes() {
      java.lang.Object ref = userLogin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLogin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string userLogin = 6;</code>
     */
    public Builder setUserLogin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userLogin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string userLogin = 6;</code>
     */
    public Builder clearUserLogin() {
      
      userLogin_ = getDefaultInstance().getUserLogin();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *默认用户登陆参数
     * </pre>
     *
     * <code>string userLogin = 6;</code>
     */
    public Builder setUserLoginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userLogin_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bill.service.v1.FlowTempTableOperateReq)
  }

  // @@protoc_insertion_point(class_scope:bill.service.v1.FlowTempTableOperateReq)
  private static final bill.service.v1.FlowTempTableOperateReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bill.service.v1.FlowTempTableOperateReq();
  }

  public static bill.service.v1.FlowTempTableOperateReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlowTempTableOperateReq>
      PARSER = new com.google.protobuf.AbstractParser<FlowTempTableOperateReq>() {
    public FlowTempTableOperateReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FlowTempTableOperateReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FlowTempTableOperateReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlowTempTableOperateReq> getParserForType() {
    return PARSER;
  }

  public bill.service.v1.FlowTempTableOperateReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

