// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill.proto

package bill.service.v1;

public interface SaveBillReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bill.service.v1.SaveBillReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string billTypeId = 1;</code>
   */
  java.lang.String getBillTypeId();
  /**
   * <code>string billTypeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBillTypeIdBytes();

  /**
   * <code>string edStatus = 2;</code>
   */
  java.lang.String getEdStatus();
  /**
   * <code>string edStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getEdStatusBytes();

  /**
   * <code>string billJson = 3;</code>
   */
  java.lang.String getBillJson();
  /**
   * <code>string billJson = 3;</code>
   */
  com.google.protobuf.ByteString
      getBillJsonBytes();

  /**
   * <code>string billItemJson = 4;</code>
   */
  java.lang.String getBillItemJson();
  /**
   * <code>string billItemJson = 4;</code>
   */
  com.google.protobuf.ByteString
      getBillItemJsonBytes();

  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 5;</code>
   */
  java.lang.String getUserLogin();
  /**
   * <pre>
   *默认用户登陆参数
   * </pre>
   *
   * <code>string userLogin = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserLoginBytes();
}
