// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ofbizCommon.proto

package com.common.query.grpc;

public interface OfbizCommonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfbizCommonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commonData = 1;</code>
   */
  java.lang.String getCommonData();
  /**
   * <code>string commonData = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommonDataBytes();
}
