// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ofbizCommon.proto

package com.common.query.grpc;

public interface OfbizCommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfbizCommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string returnData = 1;</code>
   */
  java.lang.String getReturnData();
  /**
   * <code>string returnData = 1;</code>
   */
  com.google.protobuf.ByteString
      getReturnDataBytes();
}
